FROM continuumio/miniconda3:4.7.12-alpine

USER root

# Always use the local requirements.txt to override the cloned one
COPY requirements.txt /requirements.txt

ENV PATH=$PATH:/opt/conda/bin

RUN mkdir -p /app/continuous-intelligence \
  && apk --no-cache add git nano bash \
  && git clone https://github.com/ThoughtWorksInc/continuous-intelligence-workshop.git /app/continuous-intelligence \
  && mv /requirements.txt /app/continuous-intelligence/requirements.txt \
  && cd /app/continuous-intelligence \
  && mkdir -p /app/continuous-intelligence/data/raw \
  && pip install --no-cache-dir --no-compile -r requirements.txt \
  && conda list && conda clean -tipy \
  && python /app/continuous-intelligence/src/download_data.py \
  && python /app/continuous-intelligence/src/download_data.py --model

CMD ["/app/continuous-intelligence/start.sh"]
